version: '3.8' # Версия синтаксиса Docker Compose

services:
  # Сервис для базы данных PostgreSQL
  wallet_db:
    image: postgres:17.5-alpine # Используем официальный образ PostgreSQL, версия 13, легковесная alpine
    container_name: wallet-db # Даем имя контейнеру, чтобы его было легко найти
    environment: # Переменные окружения для настройки PostgreSQL
      POSTGRES_DB: ${POSTGRES_DB}          # Имя базы данных - будет браться из .env
      POSTGRES_USER: ${POSTGRES_USER}      # Имя пользователя - будет браться из .env
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD} # Пароль - будет браться из .env
    ports:
      - "5433:5432" # Пробрасываем порт 5432 из контейнера на порт 5432 вашей машины
    volumes:
      - wallet-db:/var/lib/postgresql/data # Сохраняем данные БД, чтобы они не терялись при перезапуске контейнера
volumes:
  wallet-db: # Объявляем именованный том для сохранения данных БД