version: '3.8'

services:

  wallet_db:
    image: postgres:17.5-alpine
    container_name: wallet-db
    environment:
      POSTGRES_DB: ${POSTGRES_DB}
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
    ports:
      - "5433:5432"
    volumes:
      - wallet-db:/var/lib/postgresql/data
volumes:
  wallet-db: